image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser

tasks:
  - init: wget -c https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.27.3.14493.tar.gz && sudo tar -xzf jetbrains-toolbox-1.27.3.14493.tar.gz -C /opt
